diplom/WebApplicationEditor/Models/Publication.cs
using BisnessLogic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApplicationEditor.Models
{
    public class Publication
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Annotation { get; set; }
        public DateTime DateCreate { get; set; }
        public DateTime DatePublic { get; set; }
        public byte[] Text { get; set; }
        public string Status { get; set; }
        public List<Autor> Autors { get; set; }
        //public List<int> AutorsId { get; set; }
        public List<string> KeyWords { get; set; }
        public List<string> Categories { get; set; }

        public int? ReviewerId { get; set; }
        public string ReviewerFIO { get; set; }
    }
}

diplom/WebApplicationEditor/Controllers/EditorController.cs
using BisnessLogic.Helper;
using BisnessLogic.Models;
using Dapper;
using Database;
using Database.Logic;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace ApplicationEditor.Controllers
{
    public class EditorController : Controller
    {
        IDbConnection database = Program.database;
        MailLogic mLogic;
        List<User> users;
        List<ApplicationEditor.Models.Publication> publications;
        public EditorController()
        {
            mLogic = new MailLogic();
            users = UserLogic.GetAllUser(database);
            publications = GetPublications();
        }

        [HttpGet]
        public IActionResult Enter()
        {
            return View("Enter", new string[] { });
        }

        [HttpPost]
        public IActionResult Enter(string login, string pass)
        {
            var dp = new DynamicParameters();
            dp.Add("id", "%");
            dp.Add("login", login);

            var editor = database.Query<User>(UserLogic.GetUsers, dp).ToList();
            if (editor == null || editor.Count == 0)
                return View("Enter", new string[] { "Ошибка!", "В системе нет пользователя с такими данными." });
            else
            {
                if (editor.ElementAt(0).IsBlock)
                    return View("Enter", new string[] { "Ошибка!", "Данный пользователь заблокирован администратором." });
                else
                {
                    //Если введен неправильный пароль
                    if (editor.ElementAt(0).Password != pass)
                        return View("Enter", new string[] { "Ошибка!", "Неправильно введен пароль." });
                    else
                    {
                        Program.editor = editor.ElementAt(0);
                        return Redirect("../Home/Main");
                    }
                }
            }
        }
        //[Authorize(Roles = "Автор")]
        [ActionName("Reviewers")]
        public IActionResult GetReviwers()
        {

            var user = users.Where(rec => rec.Role == Role.Рецензент.ToString()).ToList();
            return View("Reviewers", user);
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View(new string[] { });
        }
        [HttpPost]
        public async Task<IActionResult> Register(string login, string email, string pass,
                                    string last, string first, string otch, string work, string tel)
        {
            var user = new User
            {
                Login = login,
                Email = email,
                Password = pass,
                LastName = last,
                Phone = tel,
                Name = first,
                Otch = otch,
                Work = work,
                Role = Role.Рецензент.ToString(),
                IsBlock = false
            };
            try
            {
                //database.Execute(UserLogic.AddUser, user);
                UserLogic.AddUser(database, user);
                users = UserLogic.GetAllUser(database);
                //database.QueryAsync<User>(UserLogic.GetUsers, dp).Result.ToList();
                await SendMail(user);
                return View(new string[] { "Поздравляем!", "Рецензент был удачно зарегистрирован в системе." });
            }
            catch (Exception) { return View(new string[] { "Ошибка!", "Пользователь с такими данными уже есть в системе." }); }
        }

        async Task SendMail(User user)
        {
            await Task.Run(() => mLogic.Send(user.Email,
                                "Регистрация в научном журнале",
                                 "Уважаемый(ая) " + user.LastName + " " + user.Name + " " + user.Otch
                                    + ", Вы были зарегистрированы в системе научного журнала как рецензент.\n" +
                                    "Ваш логин: " + user.Login + "\nВаш пароль: " + user.Password));
        }

        [HttpGet]
        public IActionResult Publications()
        {
            publications = GetPublications();
            return View((publications, "All"));
        }
        [HttpPost]
        public IActionResult GetPublicationList(string nameView, string selectedStatus = "All")
        {
            publications = GetPublications();
            var publics = publications;
            if (selectedStatus != "All")
            {
                publics = publications.Where(rec => rec.Status == selectedStatus).ToList();
            }
            if (nameView == "CreateMagazine")
                return View(nameView, (publics, selectedStatus, new string[] { }));
            else
                return View(nameView, (publics, selectedStatus));
        }
        [HttpGet]
        public IActionResult GetPublic()
        {
            var Id = Convert.ToInt32(Request.Query["Id"]);

            var publication = publications.First(rec => rec.Id == Id);
            var user = users.Where(rec => rec.Role == Role.Рецензент.ToString()).ToList();
            var files = PublicationLogic.GetAllFilePublication(database, Id);
            var rev = PublicationLogic.GetReviewByIDPublic(database, Id);
            if (rev != null)
                return View("Publication", (publication, user, new string[] { }, files, rev.CommentCorrectness));
            else
                return View("Publication", (publication, user, new string[] { }, files, ""));
        }
        public IActionResult DownloadFile(int Id)
        {

            var publication = PublicationLogic.GetAllFilePublication(database, Id).Last();
            //PublicationLogic.GetFilePublication(database, Id);
            //.GetPublications(database, id).First();
            var r = OnDowload(publication);
            return r;
        }

        public IActionResult DownloadFilePublication(int PublicId, int Id)
        {

            var publication = PublicationLogic.GetAllFilePublication(database, PublicId)
                .FirstOrDefault(rec => rec.Id == Id);
            //PublicationLogic.GetFilePublication(database, Id);
            //.GetPublications(database, id).First();
            if (publication != null)
            {
                var r = OnDowload(publication);
                return r;
            }
            else
                return new NotFoundResult();
        }

        public IActionResult OnDowload(FilePublication publication)
        {
            var text = publication.Text;
            if (publication.GetTypeFile().Length > 0)
            {
                string type = publication.GetTypeFile();
                return new FileContentResult(text, type)
                {
                    FileDownloadName = publication.Name
                };
            }
            else
                return new NotFoundResult();

        }

        [HttpPost]
        public IActionResult Update(string publicId, string reviewerId)
        {
            int revId = Convert.ToInt32(reviewerId);
            int Id = Convert.ToInt32(publicId);
            var publication = publications.First(rec => rec.Id == Id);
            var files = PublicationLogic.GetAllFilePublication(database, Id);
            try
            {


                var rev = PublicationLogic.GetReviewByIDPublic(database, Id);
                var res = PublicationLogic.UpdatePublic(database, Id, revId, Status.Отправлена_рецензенту.ToString());
                var model = new ApplicationEditor.Models.Publication
                {
                    Id = res.Id.Value,
                    Title = res.Title,
                    Annotation = res.Annotation,
                    DateCreate = res.DateCreate,
                    Status = res.Status,
                    KeyWords = res.KeyWords,
                    Categories = res.Categories,
                    Autors = res.Autors,
                    ReviewerId = res.ReviewerId,
                    ReviewerFIO = UserLogic.GetFIOUser(database, res.ReviewerId)
                };

                if (rev != null)
                    return View("Publication", (model, new List<User>(), new string[] { "Поздравляем!", "Изменения были удачно внесены." }
                    , files, rev.CommentCorrectness));
                else
                    return View("Publication", (model, new List<User>(), new string[] { "Поздравляем!", "Изменения были удачно внесены." }
                    , files, ""));
                //????????????????????????????????????
                //return View("Publication", ));
                //new EmptyResult();
            }
            catch (Exception ex)
            {
                //??????????????????????????????????????????????????????
                return View("Publication", (publication, new List<User>(), new string[] { "Ошибка!", ex.Message }
                , files, ""));
            }

        }
        [HttpPost]
        public IActionResult ClosePublication(string publicId)
        {
            int id = Convert.ToInt32(publicId);
            var res = PublicationLogic.UpdateStatusPublication(database, id, BisnessLogic.Models.Status.Отклонена.ToString(), null);
            return View("Publication", ((res, new List<User>(), new string[] { "Поздравляем!", "Изменения были удачно внесены." })));
            //new EmptyResult();
        }
        [HttpGet]
        public IActionResult CreateMagazine()
        {
            var model = publications.Where(rec => rec.Status == Status.Готова_к_публикации.ToString()).ToList();
            return View((model, new string[] { }));
        }
        [HttpGet]
        public IActionResult GetReview()
        {
            int Id = Convert.ToInt32(Request.Query["Id"]);
            var model = PublicationLogic.GetReviewByIDPublic(database, Id);
            return View((model, new string[] { }));
        }
        [HttpPost]

diplom/WebApplicationEditor/Views/Editor/CreateMagazine.cshtml
@using BisnessLogic.Models
@using ApplicationEditor.Models
@model (List<ApplicationEditor.Models.Publication>, string[])
@{
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body id="body">
    <script>

    </script>
    <script>
        var count = 0;
        var list = [];

        function Filter() {
            var status = document.getElementById('status');
            $.post("/Editor/GetPublicationList", { nameView: "CreateMagazine", selectedStatus: status.value },
                function (dataP) {
                    $('#body').html(dataP);
                    var options = document.getElementsByTagName('option');
                    for (var i = 0; i < options.length; i++) {
                        if (options.item(i).value == status.value) {
                            options.item(i).selected = true;
                            break;
                        }
                    }
                });
        }
        function Select(input) {
            //Swal.fire('checked: ' + input.checked);
            if (input.checked) {
                //Swal.fire('True');
                count = count + 1;
                list.push(input.value);
            }
            else if (!input.checked) {
                //Swal.fire('False');
                count = count - 1;
                list.pop();
            }
        }

        function Proverka() {
            if (count == 0) {
                Swal.fire('Выберите статьи!');
                return false;
            }
            /*
            if (count != 14) {
                Swal.fire('В выпуске журнала могут быть только 14 статей. Вы выбрвли ' + count + '.');
                return false;
            }
            */
        }
    </script>
    <header>
        <nav>
            <ul class="topmenu">
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Main">Научный журнал</a>
                </li>

                <li>
                    <a href="" class="submenu-link">Рецензенты</a>
                    <ul class="submenu">
                        <li><a href="../Editor/Reviewers">Список рецензентов</a></li>
                        <li><a href="../Editor/Register">Регистрация рецензента</a></li>
                    </ul>
                </li>
                <li>
                    <a class="submenu-link">Выпуски журнала</a>
                    <ul class="submenu">
                        <li><a href="../Editor/CreateMagazine">Формировать научный журнал</a></li>
                        <li><a href="../Editor/Magazines">Список выпусков</a></li>
                    </ul>
                </li>

                <li>
                    <a href="../Editor/Publications">Список статей</a>
                </li>
            </ul>
        </nav>
    </header>
    <form method="post" onsubmit="return Proverka();">
        <h1>Формирование выпуска научного журнала</h1>
        @if (Model.Item2.Length != 0)
        {
            <div class="alert alert-primary" role="alert">
                <strong>@Model.Item2.ElementAt(0)</strong>@Model.Item2.ElementAt(1)
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        <h6>Выберите статьи для формирования выпуска:</h6>
        <!--
        <label>Фильтровать:</label>
        <select id="status" onchange="Filter();">
            <option name="status" value="All">Все</option>
            <option name="status" value="@Status.Готова_к_публикации">@Status.Готова_к_публикации</option>
        </select>
            -->
        <table id="dataPublic" class="table table-primary">
            <thead>
                <tr>
                    <th>№</th>
                    <th>Название статьи</th>
                    <th>Дата подачи</th>
                    <th>Статус</th>
                    <th>Рецензент</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var str in Model.Item1)
                {
                    <tr>
                        <td>@str.Id</td>
                        <td><a href="/Editor/GetPublic?Id=@str.Id" />@str.Title</td>
                        <td>@str.DateCreate</td>
                        <td>@str.Status</td>
                        <td>@str.ReviewerFIO</td>
                        <td><input type="checkbox" name="checkbox" value="@str.Id" onclick="Select(this);" /></td>
                    </tr>
                }
            </tbody>
        </table>
        <label style="font-weight:bold">Выберите дату выхода:</label>
        <input id="date" type="date" name="date" required />
        <button class="btn btn-primary" type="submit" asp-action="CreateMagazine" asp-controller="Editor">Сформировать выпуск журнала</button>
    </form>
</body>
</html>

diplom/WebApplicationEditor/Views/Editor/Enter.cshtml
@model string[]
@{
    ViewData["Title"] = "Вход";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Вход</title>
</head>
<body>
    <script>
        function proverka() {
            var login;
            var pas;
            login = document.getElementById("TextLogin").value
            pas = document.getElementById("TextPass").value
            if ((login == '')) {
                Swal.fire("Заполните поле \"Логин\"! \nВаше сообщение не отправлено!")
                return false;
            }
            if (pas == '') {
                Swal.fire("Введите пароль")
                return false;
            }
            return true;
        }
    </script>
    <h1 style="text-align: center">Вход</h1>
    @if (Model.Length != 0)
    {
        <div class="alert alert-primary" role="alert">
            <strong>@Model.ElementAt(0)</strong> @Model.ElementAt(1)
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <form method="post" onsubmit="return proverka()">
        <p style="font-size:20px; text-align: center">
            <label style="font-weight:bold">Логин:</label><br />
            <input name="login" id="TextLogin" type="text" size="40" /><br /><br />
        </p>
        <p style="font-size:20px; text-align: center">
            <label style="font-weight:bold">Пароль:</label><br />
            <input name="pass" id="TextPass" type="password" size="40" pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^a-zA-Z0-9])\S{8,}"
                   title="Пароль должен содержать от 8 символов (английские строчные, заглавные, цифры и спец символы)" /><br /><br />
        </p>
        <p style="font-size:20px; text-align: center">
            <button id="NextStep" type="submit" class="btn btn-primary">Вход</button><br /><br />
        </p>
    </form>
</body>
</html>

diplom/WebApplicationEditor/Views/Editor/GetReview.cshtml
@using BisnessLogic.Models
@model (BisnessLogic.Models.Review, string[])
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <script>
        function updateStatus() {
            var sel = document.getElementById('status').value;
            Swal.fire('Status: ' + sel)
        }
    </script>
    <header>
        <nav>
            <ul class="topmenu">
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Main">Научный журнал</a>
                </li>

                <li>
                    <a href="" class="submenu-link">Рецензенты</a>
                    <ul class="submenu">
                        <li><a href="../Editor/Reviewers">Список рецензентов</a></li>
                        <li><a href="../Editor/Register">Регистрация рецензента</a></li>
                    </ul>
                </li>
                <li>
                    <a class="submenu-link">Выпуски журнала</a>
                    <ul class="submenu">
                        <li><a href="../Editor/CreateMagazine">Формировать научный журнал</a></li>
                        <li><a href="../Editor/Magazines">Список выпусков</a></li>
                    </ul>
                </li>

                <li>
                    <a href="../Editor/Publications">Список статей</a>
                </li>
            </ul>
        </nav>
    </header>

    <h3 style="text-align:center">Результаты рецензирования:</h3>
    <form method="post">
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <input name="PublicId" style="display:none" type="text" value="@Model.Item1.PublicId">
                    <label style="font-weight:bold">Рубрика(и):</label><br />
                    <p id="categories">
                        @foreach (var c in Model.Item1.Categories.Split(','))
                        {
                            <input id="Checkbox1" name="category" type="checkbox" value="@c" checked>@c<br />
                        }
                    </p>

                    <label style="font-weight:bold">Новизна:</label>
                    <div id="novizna">
                        @foreach (var n in Model.Item1.New.Split(','))
                        {
                            <input name="novizna" type="checkbox" value="@n" checked>@n<br />
                        }

                    </div>
                    <div>
                        <label style="font-weight:bold">Укажите, в чем именно состоит новизна:</label><br />
                        <textarea id="TextNew" style="width:auto" name="textNew" rows="10"
                                  minlength="120" required>@Model.Item1.CommentNew</textarea>
                    </div>
                    <div>
                        <label style="font-weight:bold">Корректность работы и полученных выводов:</label>
                        <p id="corect">
                            @foreach (var n in Model.Item1.Correctness.Split(','))
                            {
                                <input name="corect" type="checkbox" value="@n" checked>@n<br />
                            }
                        </p>

                    </div>

                    <div id="TextErorrs">
                        @if (Model.Item1.CommentCorrectness != null && Model.Item1.CommentCorrectness.Length > 0)
                        {
                            <label style="font-weight:bold">Укажите, в чем именно содержатся ошибки:</label><br />
                            <textarea id="TextNew" style="width:auto" name="textNew" rows="10"
                                      minlength="120" required>@Model.Item1.CommentCorrectness</textarea>
                        }
                    </div>

                    <div>
                        <label style="font-weight:bold">Значимость работы:</label><br>
                        <p id="znach">
                            @foreach (var n in Model.Item1.Znach.Split(','))
                            {
                                <input name="znach" type="checkbox" value="@n" checked>@n<br />
                            }
                        </p>
                    </div>
                    <div>
                        <label style="font-weight:bold">
                            Укажите, для какого круга специалистов статья будет интересна, в том числе
                            практическую значимость работы, оцените перспективу реализации результатов.
                        </label>
                        <textarea id="TextZnach" name="textZnach" rows="10" minlength="120" required>
                            @Model.Item1.CommentZnach</textarea>
                    </div>
                </div>

                <div class="col-sm">
                    <label style="font-weight:bold">Полнота исследования:</label>
                    <p id="polnota">
                        @foreach (var p in Model.Item1.Polnota.Split(','))
                        {
                            <input name="polnota" type="checkbox" value="@p" checked>@p<br />
                        }
                    </p>
                    <div>
                        @if (Model.Item1.CommentPolnota != null && Model.Item1.CommentPolnota.Length > 0)
                        {
                            <label style="font-weight:bold">Распишите более подробно:</label><br />
                            <textarea id="textPolnota" name="textPolnote" rows="10" minlength="120">
                            @Model.Item1.CommentPolnota</textarea><br />
                        }
                    </div>

                    <label style="font-weight:bold">Ясность изложения:</label>
                    <p id="izloj">
                        @foreach (var i in Model.Item1.Clarity.Split(','))
                        {
                            <input name="izloj" type="checkbox" checked
                                   value="@i">@i<br />
                            }
                    </p>
                    <div>
                        @if (Model.Item1.CommentClarity != null && Model.Item1.CommentClarity.Length > 0)
                        {
                            <label style="font-weight:bold">Распишите более подробно:</label><br />
                            <textarea id="textPolnota" name="textPolnote" rows="10" minlength="120">
                            @Model.Item1.CommentClarity</textarea><br />
                        }
                    </div>

                    <label style="font-weight:bold">Рекомендации:</label>
                    <p id="recomend">
                        @foreach (var r in Model.Item1.Recomend.Split(','))
                        {
                            <input name="recomends" type="checkbox" checked
                                   value="@r">@r<br />
                            }
                    </p>
                    <div>
                        @if (Model.Item1.CommentRecomend != null && Model.Item1.CommentRecomend.Length > 0)
                        {
                            <label style="font-weight:bold">Распишите более подробно:</label><br />
                            <textarea id="textRecomend" name="textRecomend" rows="10" minlength="120">
                            @Model.Item1.CommentRecomend</textarea><br />
                        }
                    </div>
                </div>

                <div class="col-sm">
                    <label style="font-weight:bold">Общее впечатление от работы:</label>
                    <p id="result">
                        @foreach (var r in Model.Item1.Result.Split(','))
                        {
                            <input name="results" type="checkbox" checked
                                   value=@r>@r<br />
                            }
                    </p>
                    <label style="font-weight:bold">Приведите ниже развернутую оценку содержания статьи:</label><br />
                    <textarea id="TextResult" name="textResult" rows="10" minlength="120" required>
                        @Model.Item1.CommentResult</textarea><br />
                    <label style="font-weight:bold">
                        Наличие обязательных блоков текста: аннотации, ключевых слов, списка источников, авторского блока с адресами.
                        Соответствие техническим требованиям оформления: параметры страниц, стили, иллюстрации, библиография, рекомендуемый объем.
                    </label>
                    <p id="blocks">
                        @foreach (var b in Model.Item1.HasBlocks.Split(','))
                        {
                            <input id="result1" name="blocks" type="checkbox" checked
                                   value="@b">@b<br />
                            }
                    </p>
                    <label style="font-weight:bold">Заключение о публикации статьи:</label>
                    <p id="zakl">
                        @foreach (var z in Model.Item1.Conclusion.Split(','))
                        {
                            <input name="zakls" type="checkbox" checked
                                   value="@z">@z<br />
                            }
                    </p>
                </div>
            </div>

            <div class="row">
                @if (Model.Item2.Length != 0)
                {
                    <div class="alert alert-primary" role="alert">
                        <strong>@Model.Item2.ElementAt(0)</strong>@Model.Item2.ElementAt(1)
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <br />
                }
                <br />
                <label style="font-weight:bold">Решение:</label>
                <label>Перевести данную статью в статус:</label>
                <select id="status" name="status" required>
                    <option selected disabled value="">Выберите...</option>
                    <option value="@Status.Готова_к_публикации">@Status.Готова_к_публикации</option>
                    <option value="@Status.Устранить_замечания_редактора">@Status.Устранить_замечания_редактора</option>
                    <option value="@Status.Устранить_замечания_рецензента">@Status.Устранить_замечания_рецензента</option>
                </select>
                <button id="Save" class="btn btn-primary" type="submit" asp-controller="Editor" asp-action="UpdateStatus">Изменить</button>
            </div>
        </div>
    </form>
</body>
</html>

diplom/WebApplicationEditor/Views/Editor/Magazine.cshtml
@model BisnessLogic.Models.Magazine
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <header>
        <nav>
            <ul class="topmenu">
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Main">Научный журнал</a>
                </li>

                <li>
                    <a href="" class="submenu-link">Рецензенты</a>
                    <ul class="submenu">
                        <li><a href="../Editor/Reviewers">Список рецензентов</a></li>
                        <li><a href="../Editor/Register">Регистрация рецензента</a></li>
                    </ul>
                </li>
                <li>
                    <a class="submenu-link">Выпуски журнала</a>
                    <ul class="submenu">
                        <li><a href="../Editor/CreateMagazine">Формировать научный журнал</a></li>
                        <li><a href="../Editor/Magazines">Список выпусков</a></li>
                    </ul>
                </li>

                <li>
                    <a href="../Editor/Publications">Список статей</a>
                </li>
            </ul>
        </nav>
    </header>
    <h1>Выпуск научного журнала № @Model.Id</h1>
    <label style="font-weight:bold">Дата выпуска:</label><br />
    <input type="text" value="@Model.Date.Date"><br />
    <label style="font-weight:bold; text-align:center">Статьи в выпуске:</label>
    <table class="table table-primary">
        <thead>
            <tr>
                <th>Название статии</th>
                <th>Авторы статьи</th>
            </tr>
        </thead>
        <tbody id="users">
            @foreach (var m in Model.Publications)
            {
                <tr>
                    <td>
                        <a href="/Editor/GetPublic?Id=@m.Id">@m.Title</a>
                    </td>
                    <td>@string.Join(',', m.Autors.Select(rec => rec.GetFIOAutor()).ToArray())</td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>